### ISSUE TITLE
QIF no longer uses passed date_fmt to format timestamps

### ISSUE THREAD

**Issue by jzwick-narmi** [reubano/csv2ofx#108]
https://github.com/reubano/csv2ofx/commit/1962d52d156bba3e78d1b1fbca0c09643ee74bb4#diff-e701df6fa452caab0d4e8464ea7dfdf6c9806117a7c43db9504c6edf50d14b41L186

^ this change forces the timestamp format to be static and unconfigurable, doesn't seem that it was intentional.

**Comment by sphakka** [comment]
Has this been restored? I still see the [rogue line](https://github.com/reubano/csv2ofx/blob/04b78efaee519a33eccb095c9b4a5a034de4a290/csv2ofx/qif.py#L192)...
