### ISSUE TITLE
Account mapping does not work

### ISSUE THREAD

**Issue by pmunin** [reubano/csv2ofx#19]
Running example Python script for some Chase account activity CSV throws an error for mapped account:

```
mapping = {
    'bank': 'Chase',
    'account': 'Savings',
    'date': itemgetter('Post Date'),
    'amount': itemgetter('Amount'),
    'check_num': itemgetter('Check or Slip #'),
    'desc' : itemgetter('Description')
    }

Error: KeyError, 'Savings'
```

I tried to use any combination of account - always throw that error for whatever I specify in account property.

I'm testing it on Windows 7 x64 platform, using Anaconda python

**Comment by reubano** [comment]
Can you please post a sample csv file?

**Comment by pmunin** [comment]
@reubano , I see that you called the BUGFIX Allow static ‘account’ key, however, please be aware that it didn't work for lambda expression either. I tried to write code lambda r: 'my static account number', it still didn't work even though it showed other error: "None is not iterable".

**Comment by reubano** [comment]
Works fine for me. Make sure you have the most recent version, `0.20.1`.
