### ISSUE TITLE
command not found on MacOS after pip installation

### ISSUE THREAD

**Issue by oHaiyang** [reubano/csv2ofx#24]
```
> pip2 install csv2ofx

> csv2ofx
zsh: command not found: csv2ofx
```

**Comment by oHaiyang** [comment]
downloaded `https://github.com/reubano/csv2ofx/blob/master/bin/csv2ofx`  to `/usr/local/bin` and problem solved

**Comment by reubano** [comment]
hmmm, that still shouldn't be necessary. What do you get for `locate csv2ofx` or `which csv2ofx`? Mine is `/Users/reubano/Library/Python/2.7/bin/csv2ofx` it's possible that pip's binary install location isn't in your `path`.

**Comment by oHaiyang** [comment]
I deleted the file I downloaded, then uninstalled && installed csv2ofx.

then:
```
> which csv2ofx
csv2ofx not found
```

then:
```python
>>> import csv2ofx
>>> csv2ofx
<module 'csv2ofx' from '/usr/local/lib/python2.7/site-packages/csv2ofx/__init__.pyc'>
```

then I founded my `python` and `pip2` are both located at `/usr/local/Cellar/python/2.7.13_1/bin/`

looks like my `pip2` installed files to wrong place and also failed to install bin file?

**Comment by reubano** [comment]
What do you get for `ls /usr/local/Cellar/python/2.7.13_1/bin/ | grep csv2ofx`? If it's there, make sure `/usr/local/Cellar/python/2.7.13_1/bin/` is in your [`PATH`](http://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/).

**Comment by oHaiyang** [comment]
```
> ls usr/local/Cellar/python/2.7.13_1/bin/ | grep csv2ofx
ls: usr/local/Cellar/python/2.7.13_1/bin/: No such file or directory
```
I also tried `pip2 install hangups`, and got executable file at `/usr/local/bin/hangups`. Is this a problem of `csv2ofx` or just a problem of my `python` environment? If it is the second one, thank you so much and I could try to solve it myself.

**Comment by reubano** [comment]
Try the new version and let me know if the problem still persists.

**Comment by oHaiyang** [comment]
it works! thanks!
