### ISSUE TITLE
QuickBooks to OFX Problems

### ISSUE THREAD

**Issue by bsdimp** [reubano/csv2ofx#25]
So in QuickBooks 2007, I found a range of transactions and exported them by generating a report and exporting them to Excel which I saved to a .csv. In emacs, I then removed the first few lines of the report to get a file that starts with
`,,Type,Date,Num,Name,Memo,Account,Clr,Split,Amount,Balance`
and each transaction follows (the first field is always empty.

When I run csv2ofx, I'm greeted with a the help text. If I change 'Account' above to 'Fred' then I get an error that it can't find the Account field.

Any ideas what might be going amiss? Or even where to start tacking things down since there are no helpful messages at all.

My ultimate goal, btw, is to migrate from QB2007 to gnucash...

**Comment by reubano** [comment]
Take a look at the [customization section](https://github.com/reubano/csv2ofx#customization). Then (assuming the mapping is `csv2ofx/mappings/qbooks.py`) run this command to enable the new mapping file: `csv2ofx --mapping qbooks file.csv file.ofx`. You can view [this file](https://github.com/reubano/csv2ofx/blob/master/csv2ofx/mappings/custom.py) for inspiration.
