### ISSUE TITLE
ofx account_end function drops <LEDGERBAL> section  if specified balance is zero

### ISSUE THREAD

**Issue by pcr20** [reubano/csv2ofx#31]
I don't think this is intentional is it?

Line 270 of ofx.py:

if kwargs.get('balance'):

if ofx.footer is called as follows:
ofx.footer(balance=0.0)

then although the kwarg balance exists, it contains a float equal to 0.0, which Python casts to a False

suggest Line 270 is changed to:

if balance in kwargs:

Thanks for your work on this module - very helpful

Paul

**Comment by reubano** [comment]
Great catch! Would you mind submitting a PR?

**Comment by pcr20** [comment]
Done
