### ISSUE TITLE
Import multiple accounts to MoneyDance fails 

### ISSUE THREAD

**Issue by esakal** [reubano/csv2ofx#35]
Hello All,
Thank you for maintaining this library. The library mapping API, together with the custom mapping support is very welcoming and flexible.

Trying to upload a QIF file with multiple accounts into [MoneyDance](http://moneydance.com/)  fails to produce the desired results. The first transaction of each account is associated to the right account while all the others aren't.

I found the "bug" in the generated QIF that is causing it. I don't know if this is a bug in MoneyDance importer or with the generated QIF and I couldn't get that answer from MoneyDance support.

To make it work correctly with MoneyDance the QIF file have the !Type header only for the first transaction of every account

This **will not** work:
```
!Account
N4423 (Visa)
TCCard
^
!Type:CCard       <------------------- 1st transaction of the account - this list is mandatory
D01/15/18
Ptransaction 1
T-222.00
^
!Type:CCard         <------------------ not the 1st transaction of the account - this line is problematic
D01/15/18
Ptransaction 2
T-222.00
^
```

This **will** work:
```
!Account
N4423 (Visa)
TCCard
^
!Type:CCard       <------------------- first transaction of the account - this list is mandatory
D01/15/18
Ptransaction 1
T-222.00
^
D01/15/18
Ptransaction 2
T-222.00
^
```

I forked the library and found it quite easy to fix the "bug". I can create a PR for that but I wanted consult with you about it first to see if this is a something you will merge to the library. I was thinking about extending the mapping the following configuration:
- Option 1 (focus on the change): 'multiple_accounts_strategy' : 'default' (backward compatible) | **'first_transaction'**
- Option 2 (focus on the target): 'target_app': '' (this is the default) | **'moneydance'**

I would appreciate your insights.
Eran.

**Comment by reubano** [comment]
I think itd be best to reference the qif spec to figure out which option is correct. Next time im at my laptop ill look it up, if you havent already.

**Comment by esakal** [comment]
Hi @reubano ,
I couldn't find the official QIF specification but I researched about it quite a lot. From what I saw it might be a bug in this library, but again I didn't find the official spec.

if this is a bug in csv2ofx library then we should consider changing the default generated file. If needed it is possible to add `legacy` flag that will follow the current format but it wouldn't be the default (the change will be breaking change). 

If you will find out the those three applications mentioned below using incorrect QIF format, still I would recommend supporting it since those applications are quite familiar . If so we should obviously leave the default behavior as-is and provide a relevant mapping flag for the new format.

Hopefully I was clear. What do you think?
Thanks,
Eran.

 I'm basing my answer on the following tests:
1. In [MoneyMS QIF Specification](http://moneymvps.org/articles/qifspecification.aspx) scroll to section 'Normal Transactions Example'. You will see there that only the first transaction has the `!Type` header.
2. In MoneyDance app I showed in the first post that they export the type only for the first transaction of every account
3. the following is an export from [Banktivity application](https://www.iggsoftware.com/) 
```
!Account
NBank Leumi
TBank
^
!Type:Bank                  <----------- only on the first transaction
D01/01/2017
T164,885.30
PSTARTING BALANCE
MBALANCE ADJUSTMENT
^
D02/02/2018        <----------------- !Type was not set on the second transaction
T-11.00
Pfox
```

**Comment by reubano** [comment]
Thats enough to convince me :). Feel free to submit a pr fixing the qif output.

**Comment by reubano** [comment]
FWII, I added a [QIF spec doc](https://github.com/reubano/csv2ofx/blob/features/docs/qif-file-format.txt) I found online somewhere...
