### ISSUE TITLE
Add option to specify date format. Also add message to inform user of hidden transactions.

### ISSUE THREAD

**Issue by jarobase** [reubano/csv2ofx#39]
The following archive contains a mapping function: bpn.py which works with BNP Paribas Fortis CSV files and a csv file containing data that are not properly parsed by csv2ofx.

[problem_parsing_csv.zip](https://github.com/reubano/csv2ofx/files/1737730/problem.zip)

When bpn.py is properly installed, csv2ofx is launched with the following command:
```
$ csv2ofx -m bnp -q  problem.csv
!Account
NBNP courant
TBank
^
!Type:Bank
D01/01/01
Pfoo
Mbar
T-500000.00
^
```
Only the first line is added. It seems that the date ('Date valeur', the third column) cannot be parsed but I cannot understand why. 

```
$ cat problem.csv 
sequence,plop,Date valeur,Montant,Devise du compte,CONTREPARTIE DE LA TRANSACTION,Details,Numero
2018-1515,01/01/01,01/01/01,-500000,EUR,foo,bar,42
2018-0049,12/02/2018,12/02/18,-691.82,EUR,foo,bar,43
2018-0048,08/02/2018,08/02/18,-12.5,EUR,foo,bar,44
2018-0046,07/02/2018,07/02/18,-16.2,EUR,foo,bar,45
2018-0045,06/02/2018,06/02/18,-353.89,EUR,foo,bar,46
2018-0044,05/02/2018,04/02/18,-150,EUR,foo,bar,47

```

As the csv is parsed with meza.io, it uses generator that I don't know how to debug.

Thanks,

**Comment by reubano** [comment]
The dates are being interpreted as `MM/DD/YY` instead of `DD/MM/YY`. This is causing the "future" transactions [to be hidden](https://github.com/reubano/csv2ofx#cli-examples) via `--end` which defaults to the current date.

**Comment by jarobase** [comment]
Thanks for your response. I will try to update my data.
Regards

**Comment by zgypa** [comment]
Yes, more specifically, `csv2ofx.__init__.transaction_data` is the one doing the data parsing, in the line:

`'date': parse(date),`

If one adds the argument `dayfirst=True` the problem is solved:

`'date': parse(date, dayfirst = True),`

however this cannot be hard coded, and should probably come from locale settings, or trickled down in a `kwargs`.

What i am currently doing, is cleaning up the date at the source level, reformatting it in an unambiguous format, like the one supported in OFX, `strftime('%Y%m%d%H%M%S')`.

**Comment by reubano** [comment]
@zgypa exactly! If you wouldn't mind submitting a PR that adds a new `dayfirst` option to the CLI, I'd gladly accept it :)

**Comment by reubano** [comment]
I'm pushing commits to add `dayfirst` and `parse_fmt` options which should give you the freedom to choose how transaction dates should be parsed.

e.g,

```python
mapping = {
    'dayfirst': True
    ...
}
```

or 

```python
mapping = {
    'parse_fmt': '%d/%m/%Y'
    ...
}
```
