### ISSUE TITLE
Documentation: How do I get <LEDGERBAL> in opfx file? 

### ISSUE THREAD

**Issue by SebastiaanSchmit23** [reubano/csv2ofx#56]
If i want a LEDGERBAL in my footer how would I get this? In CLI we can do a test file ` csv2ofx -m capitalone capitalone.csv cap.ofx` . In the code I can see that some split is needed, so I assumed -S as it would be in the documentation listed on github but it is not present when doing `csv2ofx -h` .

**Comment by reubano** [comment]
The mapping file needs a `balance` entry

https://github.com/reubano/csv2ofx/blob/0cf9432ab90dc1fc02237800592fce1462720037/csv2ofx/mappings/custom.py#L5-L23

The [capitalone](https://github.com/reubano/csv2ofx/blob/master/csv2ofx/mappings/capitalone.py) mapping is missing this.

**Comment by reubano** [comment]
Feel to submit a PR updating the mapping
