### ISSUE TITLE
Parsing dates incorrectly

### ISSUE THREAD

**Issue by ppihus** [reubano/csv2ofx#60]
Doesn't seem to work correctly when csv has dates in `%d.%m.%Y`, which is rather common format outside of the US.

When `%d > 12`, it does save the correct date to the output.
When `%d ≤ 12`, it switches the day+month.

```
08.01.2019 => 20190801000000 # Incorrect
14.01.2019 => 20190114000000 # Correct
06.02.2019 => 20190602000000 # Incorrect
14.02.2019 => 20190214000000 # Correct
06.03.2019 => 20190603000000 # Incorrect
06.03.2019 => 20190603000000 # Incorrect
18.03.2019 => 20190318000000 # Correct
06.04.2019 => 20190604000000 # Incorrect
```
Tried fixing it on my own, but don't quite understand how parsing the dates is built here.

**Comment by wizonesolutions** [comment]
The issue is that the OFX controller doesn't appear to respect `date_fmt` at all. Only the QIF controller even checks it.

As a workaround, I recommend just transforming the date in your mapping. I'm using this mapping for a Norwegian bank with such dates. I some inspiration from https://github.com/reubano/csv2ofx/blob/master/csv2ofx/mappings/rabobank.py:

```
from __future__ import (
    absolute_import, division, print_function, unicode_literals)

from operator import itemgetter

def date_func(row):
    parts = row['Rentedato'].split('.')
    return '{}.{}.{}.'.format(parts[1], parts[0], parts[2])

mapping = {
    'has_header': True,
    'is_split': False,
    'bank': 'Etne Sparebank',
    'currency': 'NOK',
    'delimiter': '\t',
    'account': 'Etne Sparebank',
    'date': date_func,
    'amount': lambda r: r['Beløp'].replace(',', '.').replace(' ',''),
    'desc': itemgetter('Beskrivelse'),
    'payee': itemgetter('Motkonto'),
    'id': itemgetter('Arkivref'),
    'class': itemgetter('Tekstkode'),
    'date_fmt': '%d.%m.%Y',
}
```

Note the `'date'` mapping and `date_func`. I guess that it's good we can pass callbacks to mappings, since it lets us work around missing options sometimes. Useful tool.

It really threw me off as to why some transactions were missing when I imported the OFX file into _You Need A Budget_!

**Comment by reubano** [comment]
CR #39

**Comment by zzpaulzz** [comment]
Really stuck on this. For me, the date_func returns the correct formatted date (confirmed by printing out the results) but then something is processing the date again and swapping the Day<>Month when the days drops below 10.  All the solutions proposed so far are based on the 'date': date_func.  It works for other people so what might I be doing wrong?

`from __future__ import (
    absolute_import, division, print_function, unicode_literals)

from operator import itemgetter

def date_func(trxn):
    tag = trxn['Transaction Date']
    tag = tag.split('/')

    print ('{}/{}/{}'.format(tag[0], tag[1], tag[2]))
    return '{}/{}/{}'.format(tag[0], tag[1], tag[2])

mapping = {
    'has_header': True,
    'delimiter': ',',
    'bank': 'Tesco',
    'currency': 'GBP',
    'account': 'Tesco Credit',
    'date': date_func,
    'amount': itemgetter('Billing Amount'),
    'payee': itemgetter('Merchant'),
    'check_num': itemgetter('Reference Number'),
    'date_fmt': '%d/%m/%Y',
}`

**Comment by nysthee** [comment]
I have a similar experience. It get's put back to the default format.

**Comment by reubano** [comment]
`date_fmt` is used for formating QIF output, not parsing. `date` is for generating the textual representation of the transaction date, not parsing. I'm pushing commits to add `dayfirst` and `parse_fmt` options which should give you freedom to choose how transaction dates should be parsed.
