### ISSUE TITLE
Rabobank update

### ISSUE THREAD

**Issue by AxisNL** [reubano/csv2ofx#63]
I don't even know how to create a pull request, but the rabobank (Dutch bank) updated it's format. Here's the new mapping.
[rabobank.py.txt](https://github.com/reubano/csv2ofx/files/3654962/rabobank.py.txt)

**Comment by reubano** [comment]
Thanks. [Here's a link](https://help.github.com/en/articles/creating-a-pull-request) with more info on creating pull requests.

**Comment by reubano** [comment]
Closed via 72046d8abbaca77ce61a4c780d5d0b9a2a193be4
