### ISSUE TITLE
Unable to generate <LEDGERBAL> from CLI

### ISSUE THREAD

**Issue by frflores11** [reubano/csv2ofx#74]
Hi Guys!,
Thank you for your efforts to bring this much needed tool!..

I'm trying to use the CLI to generate an OFX from my bank CSV, however so far I've not been successful in generating the LEDGERBAL tag that my Accounting software seems to require... 

I've inspected the code and I understand that the tag (LEDGERBAL) is inserted by the account_end method (ofx.py:276), and that this method is called from the footer and the gen_body methods... none of those calls seems to include the parameter "balance" that is required (in account_end) to insert the LEDGERBAL tag... is that the intended behavior?  if that is the case, it is impossible to generate the LEDGERBAL tag from the CLI, am I right?

**Comment by reubano** [comment]
See #56
